#!/usr/bin/env bash
# SPDX-License-Identifier: AGPL-3.0-or-later
# Copyright (C) 2026 Ronan Lamour
# Publishes a recruit version: binaries for macOS (Apple Silicon, Intel) and Linux (x86_64, arm64, static),
# a GitHub release holding them, and the formula of the Homebrew tap that installs them.
#
#   scripts/release.sh 0.2.0 [notes.md]    publish (notes: the file, or the commit subjects since the last tag)
#   scripts/release.sh --dry-run 0.2.0     build and package only, into target/dist/0.2.0/
#   scripts/release.sh --formula 0.2.0     regenerate the tap's formula of a published release, from its SHA256SUMS
#
# Runs on a Mac: Apple's toolchain for macOS, cargo-zigbuild for Linux (brew install zig cargo-zigbuild).
# Needs gh logged in to GitHub, brew (it checks the formulae as `brew tap` does) and the tap (ronalove/homebrew-tap)
# cloned next to this repository (or TAP_DIR=…).
set -euo pipefail

REPO=ronalove/recruit
DOWNLOAD=https://github.com/$REPO/releases/download
MAC_TARGETS=(aarch64-apple-darwin x86_64-apple-darwin)
LINUX_TARGETS=(x86_64-unknown-linux-musl aarch64-unknown-linux-musl)
FILES=(LICENSE README.md README.fr.md)

die() {
  echo "release: $*" >&2
  exit 1
}

# Once the tag exists, running the script again stops at "tag already exists": the failures after it say instead where
# the release stands and what is left to run.
finish_release() {
  echo "finish the $tag release on GitHub (title, notes, the archives and SHA256SUMS in $dist), and then run: scripts/release.sh --formula $version"
}

unfinished() {
  die "$*
$tag is pushed: $(finish_release)"
}

mode=publish
case ${1:-} in
  --dry-run) mode=dry; shift ;;
  --formula) mode=formula; shift ;;
esac
version=${1:-}
notes_file=${2:-}
[[ $version =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]] || die "usage: scripts/release.sh [--dry-run | --formula] X.Y.Z [notes.md]"
tag=v$version

cd "$(dirname "$0")/.."
root=$PWD
TAP_DIR=${TAP_DIR:-$(dirname "$root")/homebrew-tap}
# rustup's cargo, not another one earlier in the PATH: Homebrew's rust ignores the targets added with rustup.
export PATH="$HOME/.cargo/bin:$PATH"
# No AppleDouble files (._recruit) in the archives.
export COPYFILE_DISABLE=1

# The check of `brew tap`: every formula must load on every system and architecture Homebrew knows, or it refuses the
# whole tap and deletes its clone (a URL only inside on_macos is enough). `brew install` and `brew update` skip it, so
# a broken tap shows only when someone taps it anew. Its errors are printed.
check_formulae() {
  command -v brew >/dev/null || die "brew not found: it checks the formulae"
  brew ruby -e '
    require "readall"
    files = ARGV.map { |file| Pathname(file).expand_path }
    exit Readall.valid_tap?(Tap.fetch("ronalove/tap"), formula_files: files, cask_files: [])
  ' "$@"
}

check_tap() {
  [[ -d $TAP_DIR/.git ]] || die "tap not found in $TAP_DIR (set TAP_DIR)"
  [[ -z $(git -C "$TAP_DIR" status --porcelain) ]] || die "the tap has changes"
  git -C "$TAP_DIR" pull -q --ff-only
  check_formulae "$TAP_DIR"/Formula/*.rb || die "a formula of the tap fails the check of brew tap (above): fix it first"
}

# Writes the tap's formula from a SHA256SUMS file into a file (the second argument).
write_formula() {
  local sums=$1 out=$2
  sha() {
    local hash
    hash=$(awk -v f="recruit-$version-$1.tar.gz" '$2 == f { print $1 }' "$sums")
    [[ -n $hash ]] || die "no checksum for $1 in SHA256SUMS"
    echo "$hash"
  }
  url() { echo "$DOWNLOAD/$tag/recruit-$version-$1.tar.gz"; }
  # Assigned first: a failure inside the here-document below would not stop the script.
  local mac_arm mac_intel linux_arm linux_intel
  mac_arm=$(sha aarch64-apple-darwin)
  mac_intel=$(sha x86_64-apple-darwin)
  linux_arm=$(sha aarch64-unknown-linux-musl)
  linux_intel=$(sha x86_64-unknown-linux-musl)
  cat >"$out" <<EOF
# Generated by scripts/release.sh in ronalove/recruit: change the script, not this file.
class Recruit < Formula
  desc "Launch teams of Claude Code agents in tmux, each knowing its role and teammates"
  homepage "https://github.com/ronalove/recruit"
  license "AGPL-3.0-or-later"

  head do
    url "https://github.com/ronalove/recruit.git", branch: "main"
    depends_on "rust" => :build
  end

  depends_on "tmux"

  on_macos do
    on_arm do
      url "$(url aarch64-apple-darwin)"
      sha256 "$mac_arm"
    end
    on_intel do
      url "$(url x86_64-apple-darwin)"
      sha256 "$mac_intel"
    end
  end

  on_linux do
    on_arm do
      url "$(url aarch64-unknown-linux-musl)"
      sha256 "$linux_arm"
    end
    on_intel do
      url "$(url x86_64-unknown-linux-musl)"
      sha256 "$linux_intel"
    end
  end

  def install
    if build.head?
      system "cargo", "install", *std_cargo_args
    else
      bin.install "recruit"
    end
  end

  def caveats
    <<~EOS
      recruit launches Claude Code, which is installed separately:
        https://claude.com/claude-code
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/recruit --version")
    system bin/"recruit", "--lang", "en", "templates"
  end
end
EOF
  ruby -c "$out" >/dev/null
}

# Writes the tap's formula from a SHA256SUMS file, checks the tap as brew tap will, then commits and pushes it.
publish_formula() {
  write_formula "$1" "$TAP_DIR/Formula/recruit.rb"
  check_formulae "$TAP_DIR"/Formula/*.rb || die "the tap fails the check of brew tap with this formula (above), nothing \
pushed: fix the template, restore the tap (git -C $(printf %q "$TAP_DIR") checkout Formula/recruit.rb), then run: \
scripts/release.sh --formula $version"
  if [[ -n $(git -C "$TAP_DIR" status --porcelain) ]]; then
    # Added first: the tap does not know the file yet when this is its first version.
    git -C "$TAP_DIR" add Formula/recruit.rb
    git -C "$TAP_DIR" commit -q -m "recruit $version" Formula/recruit.rb
    git -C "$TAP_DIR" push -q ||
      die "the tap's push failed: its commit \"recruit $version\" is only local. Push it: git -C $(printf %q "$TAP_DIR") push"
  fi
}

if [[ $mode == formula ]]; then
  echo "==> Homebrew tap, from the $tag release"
  check_tap
  sums=$(mktemp)
  curl -fsSL --retry 3 --retry-all-errors --retry-delay 2 "$DOWNLOAD/$tag/SHA256SUMS" >"$sums" || die "no SHA256SUMS in the $tag release"
  publish_formula "$sums"
  rm -f "$sums"
  echo "==> formula of recruit $version published: brew update && brew upgrade recruit"
  exit 0
fi

[[ $(uname) == Darwin ]] || die "run it on a Mac (Apple's toolchain builds the macOS binaries)"
for tool in rustup cargo cargo-zigbuild zig gh shasum curl perl; do
  command -v "$tool" >/dev/null || die "$tool not found"
done
[[ -z $notes_file || -f $notes_file ]] || die "no such notes file: $notes_file"

if [[ $mode == publish ]]; then
  [[ $(git symbolic-ref --short HEAD) == main ]] || die "not on main"
  [[ -z $(git status --porcelain) ]] || die "the working tree has changes"
  push_url=$(git remote get-url --push origin 2>/dev/null || true)
  [[ $push_url =~ ^(https://github\.com/|ssh://git@github\.com/|git@github\.com:)${REPO}(\.git)?/?$ ]] ||
    die "origin does not push to github.com/$REPO (it pushes to \"$push_url\"): git remote set-url origin https://github.com/$REPO.git"
  [[ $(gh api "repos/$REPO" --jq .permissions.push 2>/dev/null) == true ]] ||
    die "gh cannot publish to $REPO (gh auth status; gh auth switch -u ronalove)"
  git fetch -q origin
  [[ $(git rev-parse HEAD) == $(git rev-parse origin/main) ]] || die "main differs from origin/main"
  ! git rev-parse -q --verify "refs/tags/$tag" >/dev/null || die "tag $tag already exists"
  check_tap
fi

echo "==> version $version"
perl -0pi -e "s/^version = \"[^\"]*\"/version = \"$version\"/m" Cargo.toml
cargo update -q --workspace --offline

echo "==> checks"
cargo fmt --check
cargo clippy -q --all-targets --locked -- -D warnings
cargo test -q --locked >/dev/null
# The mod in mod/, embedded in the binary: read as Claude Code will load it.
if command -v claude >/dev/null; then
  claude plugin validate mod >/dev/null || die "the mod does not validate: claude plugin validate mod"
fi

echo "==> build"
rustup target add "${MAC_TARGETS[@]}" "${LINUX_TARGETS[@]}" >/dev/null 2>&1
for target in "${MAC_TARGETS[@]}"; do
  cargo build -q --release --locked --target "$target"
done
for target in "${LINUX_TARGETS[@]}"; do
  # zig warns about every link; the filter keeps any other message.
  cargo zigbuild -q --release --locked --target "$target" 2> >(grep -v -e "linker optimization setting" \
    -e "linker_messages" -e "^ *|$" -e "^ *= note" -e "^warning: linker stderr" -e "^$" >&2)
done
native=target/aarch64-apple-darwin/release/recruit
[[ $("$native" --version) == "recruit $version" ]] || die "the built binary does not say recruit $version"

echo "==> package"
dist=target/dist/$version
rm -rf "$dist"
mkdir -p "$dist"
for target in "${MAC_TARGETS[@]}" "${LINUX_TARGETS[@]}"; do
  stage=$(mktemp -d)
  cp "target/$target/release/recruit" "${FILES[@]}" "$stage/"
  tar -C "$stage" -czf "$dist/recruit-$version-$target.tar.gz" recruit "${FILES[@]}"
  rm -rf "$stage"
  printf '    %-28s %s\n' "$target" "$(file -b "target/$target/release/recruit" | cut -d, -f1-2)"
done
(cd "$dist" && shasum -a 256 ./*.tar.gz | sed 's| \./| |' >SHA256SUMS)

echo "==> check the formula"
# The formula of these archives, before anything is published (a dry run tests a change of its template).
formula=$(mktemp -d)
write_formula "$dist/SHA256SUMS" "$formula/recruit.rb"
check_formulae "$formula/recruit.rb" || die "the formula of these archives fails the check of brew tap (above): fix its template"
rm -rf "$formula"

if [[ $mode == dry ]]; then
  echo "==> dry run: archives in $dist, nothing published"
  git checkout -q -- Cargo.toml Cargo.lock
  exit 0
fi

echo "==> commit and tag $tag"
if [[ -n $(git status --porcelain Cargo.toml Cargo.lock) ]]; then
  git commit -q -m "recruit $version" Cargo.toml Cargo.lock
fi
git tag -a "$tag" -m "recruit $version"
git push -q origin main "$tag" || die "the push failed: the commit and $tag may be only local.
Push them (git push origin main $tag), then $(finish_release)"

echo "==> GitHub release"
previous=$(git describe --tags --abbrev=0 "$tag^" 2>/dev/null || true)
if [[ -n $notes_file ]]; then
  notes=$(cat "$notes_file")
else
  notes=$(git log --no-merges --format='- %s' ${previous:+"$previous.."}"$tag")
fi
notes+=$'\n\n'"Installation : \`brew install ronalove/tap/recruit\`"
gh release create "$tag" --repo "$REPO" --verify-tag --title "recruit $version" --notes "$notes" "$dist"/* >/dev/null ||
  unfinished "the GitHub release failed"

echo "==> check the downloads"
for target in "${MAC_TARGETS[@]}" "${LINUX_TARGETS[@]}"; do
  file=recruit-$version-$target.tar.gz
  got=$(curl -fsSL --retry 3 --retry-all-errors --retry-delay 2 "$DOWNLOAD/$tag/$file" | shasum -a 256 | cut -d' ' -f1) ||
    unfinished "the published $target archive could not be downloaded"
  expected=$(awk -v f="$file" '$2 == f { print $1 }' "$dist/SHA256SUMS")
  [[ $got == "$expected" ]] || unfinished "the published $target archive does not match"
done

echo "==> Homebrew tap"
publish_formula "$dist/SHA256SUMS"
echo "==> recruit $version published: brew update && brew upgrade recruit"
